%READS REPORT FILE 'report.txt' GENERATED BY 'tester_timeout.sh' SCRIPT
%FILE 'report.txt' CONTENT:
%1 LINE: <tot_energy> --> TOTAL ENERGY OF THE POWER MANAGER WITHOUT ANY KIND OF POLICY
%OTHER LINES: <energy>,<timeout> --> ENERGY WITH GIVEN TIMEOUT VALUE
clear all, close all
fid=fopen('report.txt');
index=1;
total_energy=str2num(fgetl(fid));
%-------------------------------------------
%break event time, must change if PSM changes
tbe=5;
%-------------------------------------------
while 1
   line=fgetl(fid);
   if ~ischar(line), break, end;
   line=split(line, ',');
   energy(index)=str2num(line{1,1});
   timeout(index)=str2num(line{2,1});
   index=index+1;
end
figure
hold on
title('energy savings under timeout increasing')
ylabel('Energy (J)')
xlabel('Timeout (ms)')
plot(timeout,energy)
%plot(timeout,total_energy)
grid on
