function [fitresult, gof] = createFit(NewX, Rsoc)
%CREATEFIT(NEWX,RSOC)
%  Create a fit.
%
%  Data for 'Rsoc_poly' fit:
%      X Input : NewX
%      Y Output: Rsoc
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 20-Feb-2022 15:38:12


%% Fit: 'Rsoc_poly'.
[xData, yData] = prepareCurveData( NewX, Rsoc );

% Set up fittype and options.
ft = fittype( 'poly5' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'Rsoc_poly' );
h = plot( fitresult, xData, yData );
legend( h, 'Rsoc vs. NewX', 'Rsoc_poly', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'NewX', 'Interpreter', 'none' );
ylabel( 'Rsoc', 'Interpreter', 'none' );
grid on


