function [fitresult, gof] = createFit(NewX, Voc)
%CREATEFIT(NEWX,VOC)
%  Create a fit.
%
%  Data for 'Voc_poly' fit:
%      X Input : NewX
%      Y Output: Voc
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 20-Feb-2022 15:45:18


%% Fit: 'Voc_poly'.
[xData, yData] = prepareCurveData( NewX, Voc );

% Set up fittype and options.
ft = fittype( 'poly3' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'Voc_poly' );
h = plot( fitresult, xData, yData );
legend( h, 'Voc vs. NewX', 'Voc_poly', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'NewX', 'Interpreter', 'none' );
ylabel( 'Voc', 'Interpreter', 'none' );
grid on


